export const LOAD_GETPOSTS_SUCCESS = 'LOAD_GETPOSTS_SUCCESS';
export const LOAD_GETPOSTS_FAIL = 'LOAD_GETPOSTS_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';