export const LOAD_GETPOSTS_SUCCESS = 'LOAD_GETPOSTS_SUCCESS';
export const LOAD_GETPOSTS_FAIL = 'LOAD_GETPOSTS_FAIL';
export const LOAD_GETPOST_SUCCESS = 'LOAD_GETPOST_SUCCESS';
export const LOAD_GETPOST_FAIL = 'LOAD_GETPOST_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAIL = 'CREATE_COMMENT_FAIL';